apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    service: bot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
      service: bot
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
        service: bot
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      containers:
        - name: bot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          volumeMounts:
            - name: php-config
              mountPath: /etc/php.ini
              subPath: php.ini
            - name: php-config
              mountPath: /etc/php.d/opcache.ini
              subPath: opcache.ini
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "app.fullname" . }}-env
            - secretRef:
                name: {{ include "app.fullname" . }}-secret
          env:
            - name: TEMPORAL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "app.fullname" . }}-env
                  key: TEMPORAL_ADDRESS
            {{- if .Values.searxng.enabled }}
            - name: SEARCH_BASE_URL
              value: "http://{{ include "app.searxngName" . }}:8080"
            {{- end }}
          command: ["php", "src/bot.php"]
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          volumeMounts:
            - name: php-config
              mountPath: /etc/php.ini
              subPath: php.ini
            - name: php-config
              mountPath: /etc/php.d/opcache.ini
              subPath: opcache.ini
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "app.fullname" . }}-env
            - secretRef:
                name: {{ include "app.fullname" . }}-secret
          env:
            - name: SKIP_MIGRATIONS
              value: "true"
            - name: TEMPORAL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "app.fullname" . }}-env
                  key: TEMPORAL_ADDRESS
            {{- if .Values.searxng.enabled }}
            - name: SEARCH_BASE_URL
              value: "http://{{ include "app.searxngName" . }}:8080"
            {{- end }}
          command: ["php", "src/worker.php"]
      volumes:
        - name: php-config
          configMap:
            name: {{ template "app.fullname" . }}-php-config
