apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    service: bot
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
      service: bot
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
        service: bot
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          volumeMounts:
            - name: php-config
              mountPath: /usr/local/etc/php/php.ini
              subPath: php.ini
            - name: php-config
              mountPath: /usr/local/etc/php/conf.d/opcache.ini
              subPath: opcache.ini
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "app.fullname" . }}-env
            - secretRef:
                name: {{ include "app.fullname" . }}-secret
      volumes:
        - name: php-config
          configMap:
            name: {{ template "app.fullname" . }}-php-config
