apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-env
data:
  {{- range $key, $value := .Values.env }}
    {{ $key | quote  }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "app.fullname" . }}-secret"
  labels:
    environment: "{{ .Chart.Name }}"
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.envSecrets }}
    {{ $key | quote  }}: {{ $value | quote }}
  {{- end }}
