apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    release: prometheus
spec:
  endpoints:
    - port: metrics
      interval: 1s
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
      service: bot